version: '3'
services: 
  db:
    image: mongo:4.0.0
  backend:
    image: node:10.6.0
    volumes: 
    - ./backend:/backend
    ports: 
    - 3000:3000
    command: bash -c "cd /backend && npm i && npm install -g nodemon && nodemon app.js"
  frontend: 
    image: nginx:1.15
    volumes: 
    - ./frontend:/usr/share/nginx/html
    ports: 
    - 80:80
